#!/usr/bin/env bash

git config filter.localize.clean "sed -e 's?'\$(git rev-parse --show-toplevel)'?https://raw.githubusercontent.com/NSSAC/EpiHiper-Schema/master?g'"
git config filter.localize.smudge "sed -e 's?https://raw.githubusercontent.com/NSSAC/EpiHiper-Schema/master?'\$(git rev-parse --show-toplevel)'?g'"
