#!/usr/bin/env bash

case $1 in
  --revert)
    echo revert localization
    git config --unset filter.localize.clean
    git config --unset filter.localize.smudge
    ;;
  
  *)
    echo initialize localization
    git config filter.localize.clean "sed -e 's?'\$(git rev-parse --show-toplevel)'?https://raw.githubusercontent.com/NSSAC/EpiHiper-Schema/master?g'"
    git config filter.localize.smudge "sed -e 's?https://raw.githubusercontent.com/NSSAC/EpiHiper-Schema/master?'\$(git rev-parse --show-toplevel)'?g'"
    ;;
esac

find $(git rev-parse --show-toplevel) -iname "*.json" -delete
git checkout -- $(git rev-parse --show-toplevel)

