#!/usr/bin/env bash

case $1 in
  --revert)
    echo revert localization
    git config --unset filter.localize.clean
    git config --unset filter.localize.smudge
    git config --unset diff.localize
    ;;
  
  *)
    echo initialize localization
    git config filter.localize.clean "$(git rev-parse --show-toplevel)/gitTools/localize.py clean $(git rev-parse --show-toplevel)"
    git config filter.localize.smudge "$(git rev-parse --show-toplevel)/gitTools/localize.py smudge $(git rev-parse --show-toplevel)"
    git config diff.localize.textconv "$(git rev-parse --show-toplevel)/gitTools/localize.py clean $(git rev-parse --show-toplevel)"
    ;;
esac

find $(git rev-parse --show-toplevel) -iname "*.json" -delete
git checkout -- $(git rev-parse --show-toplevel)

